spring:
  datasource:
    url: jdbc:postgresql://43.243.187.6:5432/catadb
    username: catalis
    password: c4t4l1s
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
server:
  port: 6060