spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warungpos
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none